CREATE TABLE USUARIOS_NIVEIS (
ID INT NOT NULL AUTO_INCREMENT,
NOME VARCHAR(30) NOT NULL UNIQUE,
PRIMARY KEY(ID)
);

CREATE TABLE USUARIOS (
ID INT NOT NULL AUTO_INCREMENT,
NOME VARCHAR(100) NOT NULL,
BIOGRAFIA TEXT,
SOBRENOME VARCHAR(100) NOT NULL,
SENHA_HASH VARCHAR(255) NOT NULL,
FOTO_DE_PERFIL VARCHAR(150),
NOME_DE_EXIBICAO VARCHAR(200),
EMAIL VARCHAR(100) NOT NULL UNIQUE,
DATA_DE_NASCIMENTO DATE,
NIVEL_ID INT NOT NULL,
CRIADO_QUANDO DATETIME DEFAULT CURRENT_TIMESTAMP,
PRIMARY KEY(ID),
FOREIGN KEY(NIVEL_ID)REFERENCES USUARIOS_NIVEIS(ID)
);

CREATE TABLE USUARIOS_AMIGOS (
USUARIO_1 INT NOT NULL,
USUARIO_2 INT NOT NULL,
PRIMARY KEY(USUARIO_1, USUARIO_2),
FOREIGN KEY(USUARIO_1)REFERENCES USUARIOS(ID),
FOREIGN KEY(USUARIO_2)REFERENCES USUARIOS(ID)
);

CREATE TABLE GRUPOS_STATUS (
ID INT NOT NULL AUTO_INCREMENT,
NOME VARCHAR(30) NOT NULL,
UNIQUE(NOME),
PRIMARY KEY(ID)
);

CREATE TABLE GRUPOS (
ID INT NOT NULL AUTO_INCREMENT,
NOME VARCHAR(100) NOT NULL,
CODIGO CHAR(10) NOT NULL UNIQUE,
CRIADO_QUANDO DATETIME DEFAULT CURRENT_TIMESTAMP,
STATUS_ID INT NOT NULL,
PRIMARY KEY(ID),
FOREIGN KEY(STATUS_ID)REFERENCES GRUPOS_STATUS(ID)
);

CREATE TABLE CONVERSAS (
ID INT NOT NULL AUTO_INCREMENT,
GRUPO_ID INT NOT NULL,
NOME VARCHAR(100) NOT NULL,
CRIADO_QUANDO DATETIME DEFAULT CURRENT_TIMESTAMP,
PRIMARY KEY(ID),
FOREIGN KEY(GRUPO_ID) REFERENCES GRUPOS(ID)
);

CREATE TABLE MENSAGENS (
ID INT NOT NULL AUTO_INCREMENT,
USUARIO_ID INT NOT NULL,
CONVERSA_ID INT NOT NULL,
CONTEUDO TEXT NOT NULL,
CRIADO_QUANDO DATETIME DEFAULT CURRENT_TIMESTAMP,
PRIMARY KEY(ID),
FOREIGN KEY(USUARIO_ID) REFERENCES USUARIOS(ID),
FOREIGN KEY(CONVERSA_ID) REFERENCES CONVERSAS(ID)
);

CREATE TABLE MATERIAS (
ID INT NOT NULL AUTO_INCREMENT,
NOME VARCHAR(100)NOT NULL UNIQUE,
CRIADO_QUANDO DATETIME DEFAULT CURRENT_TIMESTAMP,
PRIMARY KEY(ID)
);

CREATE TABLE MATERIAIS_TIPOS (
ID INT NOT NULL AUTO_INCREMENT,
NOME VARCHAR(30) NOT NULL,
UNIQUE(NOME),
PRIMARY KEY(ID)
);

CREATE TABLE MATERIAIS_VALIDACOES (
ID INT NOT NULL AUTO_INCREMENT,
NOME VARCHAR(30) NOT NULL,
UNIQUE(NOME),
PRIMARY KEY(ID)
);

CREATE TABLE MATERIAIS (
ID INT NOT NULL AUTO_INCREMENT,
NOME VARCHAR(100)NOT NULL UNIQUE,
CAMINHO VARCHAR(150) NOT NULL UNIQUE,
CRIADO_QUANDO DATETIME DEFAULT CURRENT_TIMESTAMP,
VALIDADO_ID INT NOT NULL,
TIPO_ID INT NOT NULL,
PRIMARY KEY(ID),
FOREIGN KEY(TIPO_ID)REFERENCES MATERIAIS_TIPOS(ID),
FOREIGN KEY(VALIDADO_ID)REFERENCES MATERIAIS_VALIDACOES(ID)
);

CREATE TABLE FAVORITOS (
ID INT NOT NULL AUTO_INCREMENT,
POSICAO INT,
USUARIO_ID INT NOT NULL,
MATERIAL_ID INT NOT NULL,
PRIMARY KEY(ID),
FOREIGN KEY(MATERIAL_ID)REFERENCES MATERIAIS(ID),
FOREIGN KEY(USUARIO_ID)REFERENCES USUARIOS(ID)
);

CREATE TABLE AVALIACOES (
NOTA INT NOT NULL CHECK (NOTA BETWEEN 1 AND 5),
COMENTARIO TEXT NOT NULL,
MATERIAL_ID INT NOT NULL,
USUARIO_ID INT NOT NULL,
PRIMARY KEY(MATERIAL_ID, USUARIO_ID),
FOREIGN KEY (MATERIAL_ID) REFERENCES MATERIAIS(ID),
FOREIGN KEY (USUARIO_ID) REFERENCES USUARIOS(ID)
);

CREATE TABLE GENEROS (
ID INT NOT NULL AUTO_INCREMENT,
NOME VARCHAR(100)NOT NULL UNIQUE,
CRIADO_QUANDO DATETIME DEFAULT CURRENT_TIMESTAMP,
PRIMARY KEY(ID)
);

CREATE TABLE SOLICITACOES (
USUARIO_REQUISITOR INT NOT NULL,
USUARIO_REQUISITADO INT NOT NULL,
PRIMARY KEY(USUARIO_REQUISITOR, USUARIO_REQUISITADO),
FOREIGN KEY(USUARIO_REQUISITOR) REFERENCES USUARIOS(ID),
FOREIGN KEY(USUARIO_REQUISITADO) REFERENCES USUARIOS(ID)
);

CREATE TABLE SUBGENEROS (
ID INT NOT NULL AUTO_INCREMENT,
CRIADO_QUANDO DATETIME DEFAULT CURRENT_TIMESTAMP,
NOME VARCHAR(100)NOT NULL,
GENERO_ID INT NOT NULL,
UNIQUE(GENERO_ID, NOME),
PRIMARY KEY(ID),
FOREIGN KEY(GENERO_ID)REFERENCES GENEROS(ID)
);

CREATE TABLE GRUPOS_MATERIAS (
MATERIA_ID INT NOT NULL,
GRUPO_ID INT NOT NULL,
PRIMARY KEY(MATERIA_ID, GRUPO_ID),
FOREIGN KEY(MATERIA_ID)REFERENCES MATERIAS(ID),
FOREIGN KEY(GRUPO_ID)REFERENCES GRUPOS(ID)
);

CREATE TABLE GRUPOS_MATERIAIS (
MATERIAL_ID INT NOT NULL,
GRUPO_ID INT NOT NULL,
PRIMARY KEY(MATERIAL_ID, GRUPO_ID),
FOREIGN KEY(MATERIAL_ID)REFERENCES MATERIAIS(ID),
FOREIGN KEY(GRUPO_ID)REFERENCES GRUPOS(ID)
);

CREATE TABLE GRUPOS_SUBGENEROS (
SUBGENERO_ID INT NOT NULL,
GRUPO_ID INT NOT NULL,
PRIMARY KEY(SUBGENERO_ID, GRUPO_ID),
FOREIGN KEY(SUBGENERO_ID)REFERENCES SUBGENEROS(ID),
FOREIGN KEY(GRUPO_ID)REFERENCES GRUPOS(ID)
);

CREATE TABLE GRUPOS_GENEROS (
GENERO_ID INT NOT NULL,
GRUPO_ID INT NOT NULL,
PRIMARY KEY(GENERO_ID, GRUPO_ID),
FOREIGN KEY(GENERO_ID)REFERENCES GENEROS(ID),
FOREIGN KEY(GRUPO_ID)REFERENCES GRUPOS(ID)
);

CREATE TABLE GRUPOS_USUARIOS (
USUARIO_ID INT NOT NULL,
GRUPO_ID INT NOT NULL,
PRIMARY KEY(USUARIO_ID, GRUPO_ID),
FOREIGN KEY(USUARIO_ID)REFERENCES USUARIOS(ID),
FOREIGN KEY(GRUPO_ID)REFERENCES GRUPOS(ID)
);

CREATE TABLE MATERIAIS_GENEROS (
GENERO_ID INT NOT NULL,
MATERIAL_ID INT NOT NULL,
PRIMARY KEY(GENERO_ID, MATERIAL_ID),
FOREIGN KEY(GENERO_ID)REFERENCES GENEROS(ID),
FOREIGN KEY(MATERIAL_ID)REFERENCES MATERIAIS(ID)
);

CREATE TABLE MATERIAIS_SUBGENEROS (
SUBGENERO_ID INT NOT NULL,
MATERIAL_ID INT NOT NULL,
PRIMARY KEY(SUBGENERO_ID, MATERIAL_ID),
FOREIGN KEY(SUBGENERO_ID)REFERENCES SUBGENEROS(ID),
FOREIGN KEY(MATERIAL_ID)REFERENCES MATERIAIS(ID)
);

CREATE TABLE MATERIAIS_MATERIAS (
MATERIA_ID INT NOT NULL,
MATERIAL_ID INT NOT NULL,
PRIMARY KEY(MATERIA_ID, MATERIAL_ID),
FOREIGN KEY(MATERIA_ID)REFERENCES MATERIAS(ID),
FOREIGN KEY(MATERIAL_ID)REFERENCES MATERIAIS(ID)
);