<?php
$sql = [
    "create" => [
        "CREATE TABLE USUARIOS_NIVEIS (
        ID INT NOT NULL AUTO_INCREMENT,
        NOME VARCHAR(30) NOT NULL UNIQUE,
        PRIMARY KEY(ID)
        );",

        "CREATE TABLE USUARIOS (
        ID INT NOT NULL AUTO_INCREMENT,
        NOME VARCHAR(100) NOT NULL,
        BIOGRAFIA TEXT,
        SOBRENOME VARCHAR(100) NOT NULL,
        SENHA_HASH VARCHAR(255) NOT NULL,
        FOTO_DE_PERFIL VARCHAR(150),
        NOME_DE_EXIBICAO VARCHAR(200),
        EMAIL VARCHAR(100) NOT NULL UNIQUE,
        DATA_DE_NASCIMENTO DATE,
        NIVEL_ID INT NOT NULL,
        CRIADO_QUANDO DATETIME DEFAULT CURRENT_TIMESTAMP,
        PRIMARY KEY(ID),
        FOREIGN KEY(NIVEL_ID)REFERENCES USUARIOS_NIVEIS(ID)
        );",

        "CREATE TABLE USUARIOS_AMIGOS (
        USUARIO_1 INT NOT NULL,
        USUARIO_2 INT NOT NULL,
        PRIMARY KEY(USUARIO_1, USUARIO_2),
        FOREIGN KEY(USUARIO_1)REFERENCES USUARIOS(ID) ON DELETE CASCADE,
        FOREIGN KEY(USUARIO_2)REFERENCES USUARIOS(ID) ON DELETE CASCADE
        );",

        "CREATE TABLE GRUPOS_STATUS (
        ID INT NOT NULL AUTO_INCREMENT,
        NOME VARCHAR(30) NOT NULL,
        UNIQUE(NOME),
        PRIMARY KEY(ID)
        );",

        "CREATE TABLE GRUPOS (
        ID INT NOT NULL AUTO_INCREMENT,
        NOME VARCHAR(100) NOT NULL,
        CODIGO CHAR(10) NOT NULL UNIQUE,
        CRIADO_QUANDO DATETIME DEFAULT CURRENT_TIMESTAMP,
        STATUS_ID INT NOT NULL,
        PRIMARY KEY(ID),
        FOREIGN KEY(STATUS_ID)REFERENCES GRUPOS_STATUS(ID)
        );",

        "CREATE TABLE CONVERSAS (
        ID INT NOT NULL AUTO_INCREMENT,
        GRUPO_ID INT NOT NULL,
        NOME VARCHAR(100) NOT NULL,
        CRIADO_QUANDO DATETIME DEFAULT CURRENT_TIMESTAMP,
        PRIMARY KEY(ID),
        FOREIGN KEY(GRUPO_ID) REFERENCES GRUPOS(ID) ON DELETE CASCADE
        );",

        "CREATE TABLE MENSAGENS (
        ID INT NOT NULL AUTO_INCREMENT,
        USUARIO_ID INT NOT NULL,
        CONVERSA_ID INT NOT NULL,
        CONTEUDO TEXT NOT NULL,
        CRIADO_QUANDO DATETIME DEFAULT CURRENT_TIMESTAMP,
        PRIMARY KEY(ID),
        FOREIGN KEY(USUARIO_ID) REFERENCES USUARIOS(ID) ON DELETE CASCADE,
        FOREIGN KEY(CONVERSA_ID) REFERENCES CONVERSAS(ID) ON DELETE CASCADE
        );",

        "CREATE TABLE MATERIAS (
        ID INT NOT NULL AUTO_INCREMENT,
        NOME VARCHAR(100)NOT NULL UNIQUE,
        CRIADO_QUANDO DATETIME DEFAULT CURRENT_TIMESTAMP,
        PRIMARY KEY(ID)
        );",

        "CREATE TABLE MATERIAIS_TIPOS (
        ID INT NOT NULL AUTO_INCREMENT,
        NOME VARCHAR(30) NOT NULL,
        UNIQUE(NOME),
        PRIMARY KEY(ID)
        );",

        "CREATE TABLE MATERIAIS_VALIDACOES (
        ID INT NOT NULL AUTO_INCREMENT,
        NOME VARCHAR(30) NOT NULL,
        UNIQUE(NOME),
        PRIMARY KEY(ID)
        );",

        "CREATE TABLE MATERIAIS (
        ID INT NOT NULL AUTO_INCREMENT,
        NOME VARCHAR(100)NOT NULL UNIQUE,
        CAMINHO VARCHAR(150) NOT NULL UNIQUE,
        CRIADO_QUANDO DATETIME DEFAULT CURRENT_TIMESTAMP,
        VALIDADO_ID INT NOT NULL,
        TIPO_ID INT NOT NULL,
        PRIMARY KEY(ID),
        FOREIGN KEY(TIPO_ID)REFERENCES MATERIAIS_TIPOS(ID),
        FOREIGN KEY(VALIDADO_ID)REFERENCES MATERIAIS_VALIDACOES(ID)
        );",

        "CREATE TABLE FAVORITOS (
        ID INT NOT NULL AUTO_INCREMENT,
        POSICAO INT,
        USUARIO_ID INT NOT NULL,
        MATERIAL_ID INT NOT NULL,
        PRIMARY KEY(ID),
        FOREIGN KEY(MATERIAL_ID)REFERENCES MATERIAIS(ID) ON DELETE CASCADE,
        FOREIGN KEY(USUARIO_ID)REFERENCES USUARIOS(ID) ON DELETE CASCADE
        );",

        "CREATE TABLE AVALIACOES (
        NOTA INT NOT NULL CHECK (NOTA BETWEEN 1 AND 5),
        COMENTARIO TEXT NOT NULL,
        MATERIAL_ID INT NOT NULL,
        USUARIO_ID INT NOT NULL,
        PRIMARY KEY(MATERIAL_ID, USUARIO_ID),
        FOREIGN KEY (MATERIAL_ID) REFERENCES MATERIAIS(ID) ON DELETE CASCADE,
        FOREIGN KEY (USUARIO_ID) REFERENCES USUARIOS(ID) ON DELETE CASCADE
        );",

        "CREATE TABLE GENEROS (
        ID INT NOT NULL AUTO_INCREMENT,
        NOME VARCHAR(100)NOT NULL UNIQUE,
        CRIADO_QUANDO DATETIME DEFAULT CURRENT_TIMESTAMP,
        PRIMARY KEY(ID)
        );",

        "CREATE TABLE SOLICITACOES (
        USUARIO_REQUISITOR INT NOT NULL,
        USUARIO_REQUISITADO INT NOT NULL,
        PRIMARY KEY(USUARIO_REQUISITOR, USUARIO_REQUISITADO),
        FOREIGN KEY(USUARIO_REQUISITOR) REFERENCES USUARIOS(ID) ON DELETE CASCADE,
        FOREIGN KEY(USUARIO_REQUISITADO) REFERENCES USUARIOS(ID) ON DELETE CASCADE
        );",

        "CREATE TABLE SUBGENEROS (
        ID INT NOT NULL AUTO_INCREMENT,
        CRIADO_QUANDO DATETIME DEFAULT CURRENT_TIMESTAMP,
        NOME VARCHAR(100)NOT NULL,
        GENERO_ID INT NOT NULL,
        UNIQUE(GENERO_ID, NOME),
        PRIMARY KEY(ID),
        FOREIGN KEY(GENERO_ID)REFERENCES GENEROS(ID) ON DELETE CASCADE
        );",

        "CREATE TABLE GRUPOS_MATERIAS (
        MATERIA_ID INT NOT NULL,
        GRUPO_ID INT NOT NULL,
        PRIMARY KEY(MATERIA_ID, GRUPO_ID),
        FOREIGN KEY(MATERIA_ID)REFERENCES MATERIAS(ID) ON DELETE CASCADE,
        FOREIGN KEY(GRUPO_ID)REFERENCES GRUPOS(ID) ON DELETE CASCADE
        );",

        "CREATE TABLE GRUPOS_MATERIAIS (
        MATERIAL_ID INT NOT NULL,
        GRUPO_ID INT NOT NULL,
        PRIMARY KEY(MATERIAL_ID, GRUPO_ID),
        FOREIGN KEY(MATERIAL_ID)REFERENCES MATERIAIS(ID) ON DELETE CASCADE,
        FOREIGN KEY(GRUPO_ID)REFERENCES GRUPOS(ID) ON DELETE CASCADE
        );",

        "CREATE TABLE GRUPOS_SUBGENEROS (
        SUBGENERO_ID INT NOT NULL,
        GRUPO_ID INT NOT NULL,
        PRIMARY KEY(SUBGENERO_ID, GRUPO_ID),
        FOREIGN KEY(SUBGENERO_ID)REFERENCES SUBGENEROS(ID)ON DELETE CASCADE,
        FOREIGN KEY(GRUPO_ID)REFERENCES GRUPOS(ID) ON DELETE CASCADE
        );",

        "CREATE TABLE GRUPOS_GENEROS (
        GENERO_ID INT NOT NULL,
        GRUPO_ID INT NOT NULL,
        PRIMARY KEY(GENERO_ID, GRUPO_ID),
        FOREIGN KEY(GENERO_ID)REFERENCES GENEROS(ID) ON DELETE CASCADE,
        FOREIGN KEY(GRUPO_ID)REFERENCES GRUPOS(ID) ON DELETE CASCADE
        );",

        "CREATE TABLE GRUPOS_USUARIOS (
        USUARIO_ID INT NOT NULL,
        GRUPO_ID INT NOT NULL,
        PRIMARY KEY(USUARIO_ID, GRUPO_ID),
        FOREIGN KEY(USUARIO_ID)REFERENCES USUARIOS(ID) ON DELETE CASCADE,
        FOREIGN KEY(GRUPO_ID)REFERENCES GRUPOS(ID) ON DELETE CASCADE
        );",

        "CREATE TABLE MATERIAIS_GENEROS (
        GENERO_ID INT NOT NULL,
        MATERIAL_ID INT NOT NULL,
        PRIMARY KEY(GENERO_ID, MATERIAL_ID),
        FOREIGN KEY(GENERO_ID)REFERENCES GENEROS(ID) ON DELETE CASCADE,
        FOREIGN KEY(MATERIAL_ID)REFERENCES MATERIAIS(ID) ON DELETE CASCADE
        );",

        "CREATE TABLE MATERIAIS_SUBGENEROS (
        SUBGENERO_ID INT NOT NULL,
        MATERIAL_ID INT NOT NULL,
        PRIMARY KEY(SUBGENERO_ID, MATERIAL_ID),
        FOREIGN KEY(SUBGENERO_ID)REFERENCES SUBGENEROS(ID) ON DELETE CASCADE,
        FOREIGN KEY(MATERIAL_ID)REFERENCES MATERIAIS(ID) ON DELETE CASCADE
        );",

        "CREATE TABLE MATERIAIS_MATERIAS (
        MATERIA_ID INT NOT NULL,
        MATERIAL_ID INT NOT NULL,
        PRIMARY KEY(MATERIA_ID, MATERIAL_ID),
        FOREIGN KEY(MATERIA_ID)REFERENCES MATERIAS(ID)ON DELETE CASCADE,
        FOREIGN KEY(MATERIAL_ID)REFERENCES MATERIAIS(ID) ON DELETE CASCADE
        );",
    ],

    "insert" => [
        "INSERT INTO USUARIOS_NIVEIS (NOME) VALUES 
        ('usuario'), 
        ('moderador'), 
        ('administrador');",

        "INSERT INTO USUARIOS (NOME, SOBRENOME, BIOGRAFIA, SENHA_HASH, FOTO_DE_PERFIL, NOME_DE_EXIBICAO, EMAIL, DATA_DE_NASCIMENTO, NIVEL_ID) VALUES
        ('lucas', 'lazaroto', 'gosto de volei e livros', 'senhaDoHash', 'EstudosEmGrupo/public/assets/images/admin.jpg', 'Lucas L.', 'lucas@example.com', '1990-01-01', 3),
        ('maria', 'silva', 'adoro estudar em grupo', 'senhaDoHash2', 'EstudosEmGrupo/public/assets/images/admin.jpg', 'Maria S.', 'maria@example.com', '1992-02-02', 3),
        ('joao', 'pereira', 'estudante de matematica', 'senhaDoHash3', 'EstudosEmGrupo/public/assets/images/admin.jpg', 'João P.', 'joao@example.com', '1995-03-03', 3),
        ('ana', 'oliveira', 'curiosa por ciencias', 'senhaDoHash4', 'EstudosEmGrupo/public/assets/images/admin.jpg', 'Ana O.', 'ana@example.com', '1993-04-04', 3),
        ('carlos', 'souza', 'gosto de historia e geografia', 'senhaDoHash5', 'EstudosEmGrupo/public/assets/images/admin.jpg', 'Carlos S.', 'carlos@example.com', '1991-05-05', 3),
        ('beatriz', 'fernandes', 'apaixonada por literatura', 'senhaDoHash6', 'EstudosEmGrupo/public/assets/images/admin.jpg', 'Beatriz F.', 'beatriz@example.com', '1994-06-06', 3),
        ('pedro', 'almeida', 'fascinado por tecnologia', 'senhaDoHash7', 'EstudosEmGrupo/public/assets/images/verde.jpg', 'Pedro A.', 'pedro@example.com', '1990-07-07', 2),
        ('juliana', 'rodrigues', 'gosto de artes e musica', 'senhaDoHash8', 'EstudosEmGrupo/public/assets/images/verde.jpg', 'Juliana R.', 'juliana@example.com', '1993-08-08', 2),
        ('rafael', 'martins', 'estudante de fisica', 'senhaDoHash9', 'EstudosEmGrupo/public/assets/images/verde.jpg', 'Rafael M.', 'rafael@example.com', '1991-09-09', 2),
        ('sophia', 'gomes', 'curiosa por biologia', 'senhaDoHash10', 'EstudosEmGrupo/public/assets/images/verde.jpg', 'Sophia G.', 'sophia@example.com', '1992-10-10', 2),
        ('gabriel', 'carvalho', 'gosto de quimica', 'senhaDoHash11', 'EstudosEmGrupo/public/assets/images/verde.jpg', 'Gabriel C.', 'gabriel@example.com', '1990-11-11', 2),
        ('isabela', 'barbosa', 'apaixonada por filosofia', 'senhaDoHash12', 'EstudosEmGrupo/public/assets/images/verde.jpg', 'Isabela B.', 'isabela@example.com', '1993-12-12', 2),
        ('luan', 'moura', 'fascinado por astronomia', 'senhaDoHash13', 'EstudosEmGrupo/public/assets/images/verde.jpg', 'Luan M.', 'luan@example.com', '1994-01-01', 2),
        ('mariana', 'costa', 'gosto de psicologia', 'senhaDoHash14', 'EstudosEmGrupo/public/assets/images/verde.jpg', 'Mariana C.', 'mariana@example.com', '1995-02-02', 2),
        ('felipe', 'rocha', 'estudante de economia', 'senhaDoHash15', 'EstudosEmGrupo/public/assets/images/verde.jpg', 'Felipe R.', 'felipe@example.com', '1996-03-03', 2),
        ('camila', 'alves', 'curiosa por sociologia', 'senhaDoHash16', 'EstudosEmGrupo/public/assets/images/verde.jpg', 'Camila A.', 'camila@example.com', '1997-04-04', 2),
        ('bruno', 'silveira', 'gosto de educacao fisica', 'senhaDoHash17', 'EstudosEmGrupo/public/assets/images/azul.jpg', 'Bruno S.', 'bruno@example.com', '1998-05-05', 1),
        ('larissa', 'tavares', 'apaixonada por gastronomia', 'senhaDoHash18', 'EstudosEmGrupo/public/assets/images/ciano.jpg', 'Larissa T.', 'larissa@example.com', '1999-06-06', 1),
        ('andrew', 'nguyen', 'fascinado por inteligencia artificial', 'senhaDoHash19', 'EstudosEmGrupo/public/assets/images/rosa.jpg', 'Andrew N.', 'andrew@example.com', '2000-07-07', 1),
        ('emily', 'chen', 'gosto de design grafico', 'senhaDoHash20', 'EstudosEmGrupo/public/assets/images/roxo.jpg', 'Emily C.', 'emily@example.com', '2001-08-08', 1),
        ('michael', 'johnson', 'estudante de engenharia', 'senhaDoHash21', 'EstudosEmGrupo/public/assets/images/vermelho.jpg', 'Michael J.', 'michael@example.com', '2002-09-09', 1),
        ('sarah', 'williams', 'curiosa por marketing', 'senhaDoHash22', 'EstudosEmGrupo/public/assets/images/azul.jpg', 'Sarah W.', 'sarah@example.com', '2003-10-10', 1),
        ('david', 'brown', 'gosto de financas', 'senhaDoHash23', 'EstudosEmGrupo/public/assets/images/ciano.jpg', 'David B.', 'david@example.com', '2004-11-11', 1),
        ('laura', 'jones', 'apaixonada por recursos humanos', 'senhaDoHash24', 'EstudosEmGrupo/public/assets/images/rosa.jpg', 'Laura J.', 'laura@example.com', '2005-12-12', 1),
        ('james', 'garcia', 'fascinado por direito', 'senhaDoHash25', 'EstudosEmGrupo/public/assets/images/rosa.jpg', 'James G.', 'james@example.com', '2006-01-01', 1),
        ('olivia', 'martinez', 'gosto de relacoes internacionais', 'senhaDoHash26', 'EstudosEmGrupo/public/assets/images/roxo.jpg', 'Olivia M.', 'olivia@example.com', '2007-02-02', 1),
        ('daniel', 'lopez', 'estudante de arquitetura', 'senhaDoHash27', 'EstudosEmGrupo/public/assets/images/vermelho.jpg', 'Daniel L.', 'daniel@example.com', '2008-03-03', 1),
        ('emma', 'gonzalez', 'curiosa por jornalismo', 'senhaDoHash28', 'EstudosEmGrupo/public/assets/images/azul.jpg', 'Emma G.', 'emma@example.com', '2009-04-04', 1),
        ('william', 'wilson', 'gosto de publicidade', 'senhaDoHash29', 'EstudosEmGrupo/public/assets/images/ciano.jpg', 'William W.', 'william@example.com', '2010-05-05', 1),
        ('ava', 'anderson', 'apaixonada por moda', 'senhaDoHash30', 'EstudosEmGrupo/public/assets/images/rosa.jpg', 'Ava A.', 'ava@example.com', '2011-06-06', 1),
        ('joseph', 'thomas', 'fascinado por musica', 'senhaDoHash31', 'EstudosEmGrupo/public/assets/images/roxo.jpg', 'Joseph T.', 'joseph@example.com', '2012-07-07', 1),
        ('mia', 'taylor', 'gosto de cinema', 'senhaDoHash32', 'EstudosEmGrupo/public/assets/images/vermelho.jpg', 'Mia T.', 'mia@example.com', '2013-08-08', 1),
        ('charles', 'moore', 'estudante de antropologia', 'senhaDoHash33', 'EstudosEmGrupo/public/assets/images/azul.jpg', 'Charles M.', 'charles@example.com', '2014-09-09', 1),
        ('amelia', 'jackson', 'curiosa por arqueologia', 'senhaDoHash34', 'EstudosEmGrupo/public/assets/images/ciano.jpg', 'Amelia J.', 'amelia.jackson@example.com', '2015-10-10', 1),
        ('henry', 'white', 'gosto de ciencias politicas', 'senhaDoHash35', 'EstudosEmGrupo/public/assets/images/rosa.jpg', 'Henry W.', 'henry@example.com', '2016-11-11', 1),
        ('sophia', 'harris', 'apaixonada por linguistica', 'senhaDoHash36', 'EstudosEmGrupo/public/assets/images/roxo.jpg', 'Sophia H.', 'sophia.harris@example.com', '2017-12-12', 1),
        ('alexander', 'clark', 'fascinado por neurociencia', 'senhaDoHash37', 'EstudosEmGrupo/public/assets/images/vermelho.jpg', 'Alexander C.', 'alexander@example.com', '2018-01-01', 1),
        ('isabella', 'lewis', 'gosto de educacao', 'senhaDoHash38', 'EstudosEmGrupo/public/assets/images/azul.jpg', 'Isabella L.', 'isabella@example.com', '2018-02-02', 1),
        ('benjamin', 'lee', 'estudante de ciencias da computacao', 'senhaDoHash39', 'EstudosEmGrupo/public/assets/images/ciano.jpg', 'Benjamin L.', 'benjamin@example.com', '2018-03-03', 1),
        ('charlotte', 'walker', 'curiosa por design de interiores', 'senhaDoHash40', 'EstudosEmGrupo/public/assets/images/rosa.jpg', 'Charlotte W.', 'charlotte@example.com', '2018-04-04', 1),
        ('elijah', 'hall', 'gosto de engenharia civil', 'senhaDoHash41', 'EstudosEmGrupo/public/assets/images/roxo.jpg', 'Elijah H.', 'elijah@example.com', '2018-05-05', 1),
        ('amelia', 'allen', 'apaixonada por ciencias ambientais', 'senhaDoHash42', 'EstudosEmGrupo/public/assets/images/vermelho.jpg', 'Amelia A.', 'amelia.allen@example.com', '2018-06-06', 1), 
        ('lucas', 'young', 'fascinado por robótica', 'senhaDoHash43', 'EstudosEmGrupo/public/assets/images/azul.jpg', 'Lucas Y.', 'lucas.young@example.com', '2018-07-07', 1),
        ('sophia', 'hernandez', 'gosto de ciencias da saude', 'senhaDoHash44', 'EstudosEmGrupo/public/assets/images/ciano.jpg', 'Sophia H.', 'sophia.hernandez@example.com', '2018-08-08', 1),
        ('mason', 'king', 'estudante de veterinaria', 'senhaDoHash45', 'EstudosEmGrupo/public/assets/images/verde.jpg', 'Mason K.', 'mason@example.com', '2018-09-09', 1),
        ('ella', 'wright', 'curiosa por fotografia', 'senhaDoHash46', 'EstudosEmGrupo/public/assets/images/roxo.jpg', 'Ella W.', 'ella@example.com', '2018-10-10', 1),
        ('logan', 'lopez', 'gosto de culinaria', 'senhaDoHash47', 'EstudosEmGrupo/public/assets/images/vermelho.jpg', 'Logan L.', 'logan@example.com', '2018-11-11', 1),
        ('zoe', 'hill', 'apaixonada por viagens', 'senhaDoHash48', 'EstudosEmGrupo/public/assets/images/azul.jpg', 'Zoe H.', 'zoe@example.com', '2018-12-12', 1),
        ('ethan', 'scott', 'fascinado por esportes', 'senhaDoHash49', 'EstudosEmGrupo/public/assets/images/ciano.jpg', 'Ethan S.', 'ethan@example.com', '2019-01-01', 1),
        ('lily', 'green', 'gosto de artesanato', 'senhaDoHash50', 'EstudosEmGrupo/public/assets/images/rosa.jpg', 'Lily G.', 'lily@example.com', '2019-02-02', 1),
        ('jacob', 'adams', 'estudante de musica', 'senhaDoHash51', 'EstudosEmGrupo/public/assets/images/roxo.jpg', 'Jacob A.', 'jacob@example.com', '2019-03-03', 1);",

        "INSERT INTO USUARIOS_AMIGOS (USUARIO_1, USUARIO_2) VALUES
        (1, 2),
        (1, 3),
        (2, 3),
        (4, 5),
        (4, 6),
        (5, 6),
        (7, 8),
        (7, 9),
        (8, 9),
        (10, 11),
        (10, 12),
        (11, 12),
        (13, 14),
        (13, 15),
        (14, 15),
        (16, 17),
        (16, 18),
        (17, 18),
        (19, 20),
        (19, 21),
        (20, 21),
        (22, 23),
        (22, 24),
        (23, 24),
        (25, 26),
        (25, 27),
        (26, 27),
        (28, 29),
        (28, 30),
        (29, 30),
        (31, 32),
        (31, 33),
        (32, 33),
        (34, 35),
        (34, 36),
        (35, 36),
        (37, 38),
        (37, 39),
        (38, 39),
        (40, 41),
        (40, 42),
        (41, 42),
        (43, 44),
        (43, 45),
        (44, 45),
        (46, 47),
        (46, 48),
        (47, 48),
        (49, 50),
        (49, 51),
        (50, 51);",

        "INSERT INTO GRUPOS_STATUS (NOME) VALUES
        ('privado'),
        ('publico');",

        "INSERT INTO GRUPOS (NOME, CODIGO, STATUS_ID) VALUES 
        ('Estudo de Matematica', 'MATH12345', 2),
        ('Ciencias da Natureza em Grupo', 'SCIENCE67', 2),
        ('Historia Viva', 'HISTORY89', 1),
        ('Literatura e Leitura', 'LIT20234', 2),
        ('Tecnologia e Inovacao', 'TECH56789', 1),
        ('Geografia Global', 'GEO12345', 2),
        ('Fisica para Todos', 'PHYSICS67', 1),
        ('Quimica em Ação', 'CHEM89012', 2),
        ('Biologia e Vida', 'BIO34567', 1),
        ('Artes e Criatividade', 'ARTS8901', 2),
        ('Educacao Fisica Ativa', 'PE123456', 1),
        ('Musica e Ritmo', 'MUSIC7890', 2),
        ('Informatica e Programacao', 'IT234567', 1),
        ('Filosofia e Pensamento', 'PHILOSO89', 2),
        ('Sociologia em Debate', 'SOC122457', 1),
        ('Economia e Negocios', 'ECON78901', 2),
        ('Direito e Cidadania', 'LAW234567', 1),
        ('Psicologia e Comportamento', 'PSYCH8901', 2),
        ('Administracao Eficaz', 'ADMIN1234', 1),
        ('Marketing Digital', 'MARKET567', 2),
        ('Engenharia e Projetos', 'ENG123456', 1),
        ('Medicina e Saude', 'MED789012', 2),
        ('Estudo de Filosofia', 'PHIL12345', 1),
        ('Grupo de Literatura', 'LIT67890', 2),
        ('Ciencias Sociais', 'SOC123457', 1),
        ('Tecnologia da Informacao', 'TECH78901', 2),
        ('Historia Mundial', 'HIST23456', 1),
        ('Biologia Marinha', 'BIO789012', 2),
        ('Artes Visuais', 'ART123456', 1),
        ('Educacao Ambiental', 'ENV78901', 2);",

        "INSERT INTO CONVERSAS (GRUPO_ID, NOME) VALUES
        (1, 'Dúvidas sobre Cálculo'),
        (2, 'Experimentos de Química'),
        (3, 'Linha do Tempo da Revolução Francesa'),
        (4, 'Análise de Dom Casmurro'),
        (5, 'Novas Tecnologias em IA'),
        (6, 'Guia de Estudo para Provas de Matemática'),
        (7, 'Recursos Online para Ciências'),
        (8, 'Prática de Conversação em Inglês'),
        (9, 'Receitas de Lasanha Caseira'),
        (10, 'Destinos Culturais no Japão'),
        (11, 'Rotina de Exercícios para Iniciantes'),
        (12, 'Artesanato com Materiais Reciclados'),
        (13, 'Composição Musical Básica'),
        (14, 'Técnicas de Fotografia para Iniciantes'),
        (15, 'Questões Sociais Atuais'),
        (16, 'Dicas para Pequenos Negócios'),
        (17, 'Cuidados com a Saúde Mental'),
        (18, 'Estratégias de Desenvolvimento Pessoal'),
        (19, 'Metodologias Educacionais Eficazes'),
        (20, 'Projetos Sustentáveis em Engenharia'),
        (21, 'Soluções para Problemas Ambientais'),
        (22, 'Avanços em Robótica'),
        (23, 'Tendências em Ciências da Saúde'),
        (24, 'Cuidados Veterinários Básicos'),
        (25, 'Ideias para Design de Interiores'),
        (26, 'Desafios na Engenharia Civil'),
        (27, 'Análise de Políticas Públicas'),
        (28, 'Estudos em Linguística Aplicada'),
        (29, 'Inovações em Biotecnologia'),
        (30, 'Técnicas de Pintura Moderna'),
        (1, 'Resolução de Equações Diferenciais'),
        (2, 'Discussão sobre Física Quântica'),
        (3, 'Impacto da Revolução Industrial'),
        (4, 'Interpretação de Poesias Clássicas'),
        (5, 'Futuro da Computação em Nuvem'),
        (6, 'Estratégias para Provas de História'),
        (7, 'Debate sobre Mudanças Climáticas'),
        (8, 'Prática de Redação Acadêmica'),
        (9, 'Culinária Internacional'),
        (10, 'Exploração Cultural na Europa'),
        (11, 'Treinamento Funcional Avançado'),
        (12, 'Reciclagem Criativa'),
        (13, 'Teoria Musical Avançada'),
        (14, 'Fotografia de Paisagens'),
        (15, 'Análise de Movimentos Sociais'),
        (16, 'Estratégias de Marketing Online'),
        (17, 'Técnicas de Meditação'),
        (18, 'Desenvolvimento de Habilidades Sociais'),
        (19, 'Inovações em Educação'),
        (20, 'Soluções Sustentáveis em Engenharia'),
        (21, 'Conservação Ambiental'),
        (22, 'Inteligência Artificial na Indústria'),
        (23, 'Avanços em Terapias Médicas'),
        (24, 'Saúde Animal e Bem-Estar'),
        (25, 'Tendências em Decoração de Interiores'),
        (26, 'Soluções Estruturais Inovadoras'),
        (27, 'Análise Econômica de Políticas Públicas'),
        (28, 'Estudos Semânticos Avançados'),
        (29, 'Aplicações da Biotecnologia na Medicina'),
        (30, 'Estilos de Pintura Contemporânea');",

        "INSERT INTO MENSAGENS (USUARIO_ID, CONVERSA_ID, CONTEUDO) VALUES
        (1, 1, 'Alguém pode me ajudar com limites?'),
        (2, 1, 'Claro! Qual é a sua dúvida?'),
        (3, 2, 'Vocês já tentaram o experimento de eletrólise?'),
        (4, 2, 'Sim, foi incrível ver a separação dos elementos!'),
        (5, 3, 'Quem pode explicar as causas da Revolução Francesa?'),
        (6, 3, 'Posso ajudar! Foi uma combinação de fatores sociais e econômicos.'),
        (7, 4, 'Alguém leu Dom Casmurro recentemente?'),
        (8, 4, 'Sim! Achei a análise do Bentinho fascinante.'),
        (9, 5, 'Quais são as últimas tendências em IA?'),
        (10, 5, 'O aprendizado profundo está avançando rapidamente.'),
        (11, 6, 'Alguém tem dicas para estudar matemática?'),
        (12, 6, 'Praticar muitos exercícios é essencial!'),
        (13, 7, 'Quais recursos online vocês recomendam para ciências?'),
        (14, 7, 'Khan Academy é uma ótima opção.'),
        (15, 8, 'Como melhorar minha conversação em inglês?'),
        (16, 8, 'Tente praticar com falantes nativos sempre que possível.'),
        (17, 9, 'Alguém tem uma boa receita de lasanha?'),
        (18, 9, 'Claro! Vou compartilhar a minha favorita.'),
        (19, 10, 'Quais são os melhores destinos culturais no Japão?'),
        (20, 10, 'Kyoto é imperdível para quem gosta de história e cultura.'),
        (21, 11, 'Qual é a melhor rotina de exercícios para iniciantes?'),
        (22, 11, 'Comece com exercícios leves e aumente gradualmente a intensidade.'),
        (23, 12, 'Alguém tem ideias para artesanato com materiais reciclados?'),
        (24, 12, 'Sim! Podemos fazer vasos com garrafas plásticas.'),
        (25, 13, 'Como compor uma música do zero?'),
        (26, 13, 'Comece com uma melodia simples e vá adicionando harmonias.'),
        (27, 14, 'Quais são as melhores técnicas de fotografia para iniciantes?'),
        (28, 14, 'Aprenda sobre composição e iluminação.'),
        (29, 15, 'Quais são os principais desafios sociais atuais?'),
        (30, 15, 'Desigualdade econômica e mudanças climáticas são grandes questões.'),
        (31, 16, 'Alguém tem dicas para pequenos negócios?'),
        (32, 16, 'Foque no atendimento ao cliente e marketing digital.'),
        (33, 17, 'Como cuidar melhor da saúde mental?'),
        (34, 17, 'Pratique meditação e mantenha uma rotina saudável.'),
        (35, 18, 'Quais estratégias ajudam no desenvolvimento pessoal?'),
        (36, 18, 'Defina metas claras e busque aprendizado contínuo.'),
        (37, 19, 'Quais são as metodologias educacionais mais eficazes?'),
        (38, 19, 'Aprendizagem ativa e ensino personalizado têm mostrado bons resultados.'),
        (39, 20, 'Quais projetos sustentáveis em engenharia vocês conhecem?'),
        (40, 20, 'Projetos de energia renovável estão em alta.'),
        (41, 21, 'Como podemos solucionar problemas ambientais?'),
        (42, 21, 'Reduzir o consumo e promover a reciclagem são passos importantes.'),
        (43, 22, 'Quais são os avanços recentes em robótica?'),
        (44, 22, 'Robôs colaborativos estão se tornando mais comuns na indústria.'),
        (45, 23, 'Quais são as tendências em ciências da saúde?'),
        (46, 23, 'Medicina personalizada e telemedicina estão crescendo rapidamente.'),
        (47, 24, 'Quais cuidados veterinários básicos devemos conhecer?'),
        (48, 24, 'Vacinação e alimentação adequada são essenciais.'),
        (49, 25, 'Quais são as últimas ideias para design de interiores?'),
        (50, 25, 'Estilos minimalistas e sustentáveis estão em alta.'),
        (51, 26, 'Quais são os maiores desafios na engenharia civil hoje?'),
        (2, 26, 'Sustentabilidade e uso de materiais inovadores são grandes temas.'),
        (3, 27, 'Como analisar políticas públicas de forma eficaz?'),
        (4, 27, 'Considere os impactos sociais, econômicos e ambientais.'),
        (5, 28, 'Quais são os estudos semânticos mais avançados atualmente?'),
        (6, 28, 'Análise de discurso e pragmática são áreas em crescimento.'),
        (7, 29, 'Quais são as aplicações da biotecnologia na medicina?'),
        (8, 29, 'Terapias genéticas e biomedicina estão revolucionando tratamentos.'),
        (9, 30, 'Quais são os estilos de pintura contemporânea mais populares?'),
        (10, 30, 'Abstracionismo e arte digital estão ganhando destaque.');",

        "INSERT INTO MATERIAS (NOME) VALUES
        ('Matematica'),
        ('Ciencias da Natureza'),
        ('Historia'),
        ('Literatura'),
        ('Tecnologia'),
        ('Geografia'),
        ('Fisica'),
        ('Quimica'),
        ('Biologia'),
        ('Artes'),
        ('Educacao Fisica'),
        ('Musica'),
        ('Informatica'),
        ('Filosofia'),
        ('Sociologia'),
        ('Economia'),
        ('Direito'),
        ('Psicologia'),
        ('Administracao'),
        ('Marketing'),
        ('Engenharia'),
        ('Medicina');",

        "INSERT INTO MATERIAIS_TIPOS (NOME) VALUES
        ('video'),
        ('prova'),
        ('atividade'),
        ('livro'),
        ('mapa de estudos');",

        "INSERT INTO MATERIAIS_VALIDACOES (NOME) VALUES
        ('valido'),
        ('nao esta valido');",

        "INSERT INTO MATERIAIS (NOME, CAMINHO, VALIDADO_ID, TIPO_ID) VALUES
        ('Video Aula de Calculo', 'EstudosEmGrupo/public/assets/materials/calculo.mp4', 1, 1),
        ('Prova de Fisica Basica', 'EstudosEmGrupo/public/assets/materials/fisica_prova.pdf', 1, 2),
        ('Atividade de Quimica Organica', 'EstudosEmGrupo/public/assets/materials/quimica_atividade.docx', 1, 3),
        ('Livro de Historia do Brasil', 'EstudosEmGrupo/public/assets/materials/historia_brasil.pdf', 1, 4),
        ('Mapa de Estudos de Biologia', 'EstudosEmGrupo/public/assets/materials/biologia_mapa.png', 1, 5),
        ('Video Aula de Programacao', 'EstudosEmGrupo/public/assets/materials/programacao.mp4', 1, 1),
        ('Prova de Matematica Avancada', 'EstudosEmGrupo/public/assets/materials/matematica_prova.pdf', 1, 2),
        ('Atividade de Literatura Brasileira', 'EstudosEmGrupo/public/assets/materials/literatura_atividade.docx', 1, 3),
        ('Livro de Filosofia Moderna', 'EstudosEmGrupo/public/assets/materials/filosofia_moderna.pdf', 1, 4),
        ('Mapa de Estudos de Economia', 'EstudosEmGrupo/public/assets/materials/economia_mapa.png', 1, 5),
        ('Video Aula de Quimica Inorganica', 'EstudosEmGrupo/public/assets/materials/quimica_inorganica.mp4', 1, 1),
        ('Prova de Historia Mundial', 'EstudosEmGrupo/public/assets/materials/historia_mundial_prova.pdf', 2, 2),
        ('Atividade de Biologia Celular', 'EstudosEmGrupo/public/assets/materials/biologia_celular_atividade.docx', 1, 3),
        ('Livro de Sociologia Contemporanea', 'EstudosEmGrupo/public/assets/materials/sociologia_contemporanea.pdf', 1, 4),
        ('Mapa de Estudos de Tecnologia da Informacao', 'EstudosEmGrupo/public/assets/materials/tecnologia_info_mapa.png', 1, 5),
        ('Video Aula de Fisica Moderna', 'EstudosEmGrupo/public/assets/materials/fisica_moderna.mp4', 2, 1),
        ('Prova de Quimica Analitica', 'EstudosEmGrupo/public/assets/materials/quimica_analitica_prova.pdf', 1, 2),
        ('Atividade de Geografia Humana', 'EstudosEmGrupo/public/assets/materials/geografia_humana_atividade.docx', 1, 3),
        ('Livro de Psicologia do Desenvolvimento', 'EstudosEmGrupo/public/assets/materials/psicologia_desenvolvimento.pdf', 2, 4),
        ('Mapa de Estudos de Marketing Digital', 'EstudosEmGrupo/public/assets/materials/marketing_digital_mapa.png', 1, 5);",

        "INSERT INTO FAVORITOS (POSICAO, USUARIO_ID, MATERIAL_ID) VALUES 
        (1, 1, 1),
        (2, 1, 2),
        (1, 2, 3),
        (2, 2, 4),
        (1, 3, 5),
        (2, 3, 6),
        (1, 4, 7),
        (2, 4, 8),
        (1, 5, 9),
        (2, 5, 10),
        (1, 6, 11),
        (2, 6, 12),
        (1, 7, 13),
        (2, 7, 14),
        (1, 8, 15),
        (2, 8, 16),
        (1, 9, 17),
        (2, 9, 18),
        (1, 10, 19),
        (2, 10, 20),
        (1, 11, 1),
        (2, 11, 3),
        (1, 12, 5),
        (2, 12, 7),
        (1, 13, 9),
        (2, 13, 11),
        (1, 14, 13),
        (2, 14, 15),
        (1, 15, 17),
        (2, 15, 19),
        (1, 16, 2),
        (2, 16, 4),
        (1, 17, 6),
        (2, 17, 8),
        (1, 18, 10),
        (2, 18, 12),
        (1, 19, 14),
        (2, 19, 16),
        (1, 20, 18),
        (2, 20, 20),
        (1, 21, 1),
        (2, 21, 4),
        (1, 22, 7),
        (2, 22, 10),
        (1, 23, 13),
        (2, 23, 16),
        (1, 24, 19),
        (2, 24, 2),
        (1, 25, 5),
        (2, 25, 8),
        (1, 26, 11),
        (2, 26, 14),
        (1, 27,17),
        (2, 27,20),
        (1, 28,3),
        (2, 28,6),
        (1, 29,9),
        (2, 29,12),
        (1, 30,15),
        (2, 30,18),
        (1, 31,2),
        (2, 31,5),
        (1, 32,8),
        (2, 32,11),
        (1, 33,14),
        (2, 33,17),
        (1, 34,20),
        (2, 34,3),
        (1, 35,6),
        (2, 35,9),
        (1, 36,12),
        (2, 36,15),
        (1, 37,18),
        (2, 37,1),
        (1, 38,4),
        (2, 38,7),
        (1, 39,10),
        (2, 39,13),
        (1, 40,16),
        (2, 40,19),
        (1, 41,3),
        (2, 41,6),
        (1, 42,9),
        (2, 42,12),
        (1, 43,15),
        (2, 43,18),
        (1, 44,1),
        (2, 44,4),
        (1, 45,7),
        (2, 45,10),
        (1, 46,13),
        (2, 46,16),
        (1, 47,19),
        (2, 47,2),
        (1, 48,5),
        (2, 48,8),
        (1, 49,11),
        (2, 49,14),
        (1, 50,17),
        (2, 50,20),
        (1, 51,2);",

        "INSERT INTO AVALIACOES (NOTA, COMENTARIO, MATERIAL_ID, USUARIO_ID) VALUES
        (5, 'Excelente material, muito útil!', 1, 1),
        (4, 'Bom conteúdo, mas poderia ser mais detalhado.', 2, 1),
        (3, 'Médio, faltou exemplos práticos.', 3, 2),
        (5, 'Ótimo para revisão!', 4, 2),
        (4, 'Informações claras e objetivas.', 5, 3),
        (2, 'Não atendeu minhas expectativas.', 6, 3),
        (5, 'Muito bem explicado!', 7, 4),
        (4, 'Conteúdo relevante.', 8, 4),
        (3, 'Poderia ter mais exercícios.', 9, 5),
        (5, 'Adorei o formato do material!', 10, 5),
        (4, 'Útil para estudos rápidos.', 11, 6),
        (5, 'Material completo e bem estruturado.', 12, 6),
        (3, 'Faltou aprofundamento em alguns tópicos.', 13, 7),
        (4, 'Bom para iniciantes.', 14, 7),
        (5, 'Recomendo para todos os estudantes!', 15, 8),
        (2, 'Não gostei da abordagem utilizada.', 16, 8),
        (4, 'Conteúdo atualizado e relevante.', 17, 9),
        (5, 'Excelente recurso de estudo!', 18, 9),
        (3, 'Poderia ser mais interativo.', 19, 10),
        (4, 'Material bem organizado.', 20, 10),
        (5, 'Muito bom para revisão rápida.', 1, 11),
        (4, 'Conteúdo interessante.', 2, 11),
        (3, 'Faltou exemplos práticos.', 3, 12),
        (5, 'Ótimo material de apoio!', 4, 12),
        (4, 'Informações claras e objetivas.', 5, 13),
        (2, 'Não atendeu minhas expectativas.', 6, 13),
        (5, 'Muito bem explicado!', 7, 14),
        (4, 'Conteúdo relevante.', 8, 14),
        (3, 'Poderia ter mais exercícios.', 9, 15),
        (5, 'Adorei o formato do material!', 10, 15),
        (4, 'Útil para estudos rápidos.', 11, 16),
        (5, 'Material completo e bem estruturado.', 12, 16),
        (3, 'Faltou aprofundamento em alguns tópicos.', 13, 17),
        (4, 'Bom para iniciantes.', 14, 17),
        (5, 'Recomendo para todos os estudantes!', 15, 18),
        (2, 'Não gostei da abordagem utilizada.', 16, 18),
        (4, 'Conteúdo atualizado e relevante.', 17, 19),
        (5, 'Excelente recurso de estudo!', 18, 19),
        (3, 'Poderia ser mais interativo.', 19, 20),
        (4, 'Material bem organizado.', 20, 20),
        (5, 'Muito bom para revisão rápida.', 1, 21),
        (4, 'Conteúdo interessante.', 2, 21),
        (3, 'Faltou exemplos práticos.', 3, 22),
        (5, 'Ótimo material de apoio!', 4, 22),
        (4, 'Informações claras e objetivas.', 5, 23),
        (2, 'Não atendeu minhas expectativas.', 6, 23),
        (5, 'Muito bem explicado!', 7, 24),
        (4, 'Conteúdo relevante.', 8, 24),
        (3, 'Poderia ter mais exercícios.', 9, 25),
        (5, 'Adorei o formato do material!', 10, 25),
        (4, 'Útil para estudos rápidos.', 11, 26),
        (5, 'Material completo e bem estruturado.', 12, 26),
        (3, 'Faltou aprofundamento em alguns tópicos.', 13, 27),
        (4, 'Bom para iniciantes.', 14, 27),
        (5, 'Recomendo para todos os estudantes!', 15, 28),
        (2, 'Não gostei da abordagem utilizada.', 16, 28),
        (4, 'Conteúdo atualizado e relevante.', 17, 29),
        (5, 'Excelente recurso de estudo!', 18, 29),
        (3, 'Poderia ser mais interativo.', 19, 30),
        (4, 'Material bem organizado.', 20, 30),
        (5, 'Muito bom para revisão rápida.', 1, 31),
        (4, 'Conteúdo interessante.', 2, 31),
        (3, 'Faltou exemplos práticos.', 3, 32),
        (5, 'Ótimo material de apoio!', 4, 32),
        (4, 'Informações claras e objetivas.', 5, 33),
        (2, 'Não atendeu minhas expectativas.', 6, 33),
        (5, 'Muito bem explicado!', 7, 34),
        (4, 'Conteúdo relevante.', 8, 34),
        (3, 'Poderia ter mais exercícios.', 9, 35),
        (5, 'Adorei o formato do material!', 10, 35),
        (4, 'Útil para estudos rápidos.', 11, 36),
        (5, 'Material completo e bem estruturado.', 12, 36),
        (3, 'Faltou aprofundamento em alguns tópicos.', 13, 37),
        (4, 'Bom para iniciantes.', 14, 37),
        (5, 'Recomendo para todos os estudantes!', 15, 38),
        (2, 'Não gostei da abordagem utilizada.', 16, 38),
        (4, 'Conteúdo atualizado e relevante.', 17, 39),
        (5, 'Excelente recurso de estudo!', 18, 39),
        (3, 'Poderia ser mais interativo.', 19, 40),
        (4, 'Material bem organizado.', 20, 40),
        (5, 'Muito bom para revisão rápida.', 1, 41),
        (4, 'Conteúdo interessante.', 2, 41),
        (3, 'Faltou exemplos práticos.', 3, 42),
        (5, 'Ótimo material de apoio!', 4, 42),
        (4, 'Informações claras e objetivas.', 5, 43),
        (2, 'Não atendeu minhas expectativas.', 6, 43),
        (5, 'Muito bem explicado!', 7, 44),
        (4, 'Conteúdo relevante.', 8, 44),
        (3, 'Poderia ter mais exercícios.', 9, 45),
        (5, 'Adorei o formato do material!', 10, 45),
        (4, 'Útil para estudos rápidos.', 11, 46),
        (5, 'Material completo e bem estruturado.', 12, 46),
        (3, 'Faltou aprofundamento em alguns tópicos.', 13, 47),
        (4, 'Bom para iniciantes.', 14, 47),
        (5, 'Recomendo para todos os estudantes!', 15, 48),
        (2, 'Não gostei da abordagem utilizada.', 16, 48),
        (4, 'Conteúdo atualizado e relevante.', 17, 49),
        (5, 'Excelente recurso de estudo!', 18, 49),
        (3, 'Poderia ser mais interativo.', 19, 50),
        (4, 'Material bem organizado.', 20, 50),
        (5, 'Muito bom para revisão rápida.', 1, 51);",

        "INSERT INTO GENEROS (NOME) VALUES
        ('Computacao'),
        ('Saude'),
        ('Engenharia'),
        ('Artes'),
        ('Ciencias Humanas'),
        ('Negocios'),
        ('Educacao'),
        ('Tecnologia'),
        ('Culinaria'),
        ('Esportes'),
        ('Musica'),
        ('Fotografia'),
        ('Viagens'),
        ('Psicologia'),
        ('Design'),
        ('Moda'),
        ('Cinema'),
        ('Literatura'),
        ('Historia'),
        ('Ciencias Sociais'),
        ('Biologia'),
        ('Quimica'),
        ('Fisica'),
        ('Matematica'),
        ('Economia'),
        ('Direito'),
        ('Administracao'),
        ('Marketing'),
        ('Informatica'),
        ('Filosofia'),
        ('Sociologia'),
        ('Medicina'),
        ('Veterinaria'),
        ('Arquitetura'),
        ('Ciencias Ambientais'),
        ('Robótica'),
        ('Inteligencia Artificial'),
        ('Neurociencia'),
        ('Jornalismo'),
        ('Publicidade'),
        ('Danca'),
        ('Teatro'),
        ('Artesanato'),
        ('Esportes Radicais'),
        ('Culinaria Saudavel'),
        ('Viagens de Aventura'),
        ('Esportes Coletivos'),
        ('Artes Digitais'),
        ('Musica Eletronica'),
        ('Cinema Independente');",

        "INSERT INTO SOLICITACOES (USUARIO_REQUISITOR, USUARIO_REQUISITADO) VALUES
        (1,3),
        (2,4),
        (3,5),
        (4,6),
        (5,7),
        (6,8),
        (7,9),
        (8,10),
        (9,11),
        (10,12),
        (11,13),
        (12,14),
        (13,15),
        (14,16),
        (15,17),
        (16,18),
        (17,19),
        (18,20),
        (19,21),
        (20,22),
        (21,23),
        (22,24),
        (23,25),
        (24,26),
        (25,27),
        (26,28),
        (27,29),
        (28,30),
        (29,31),
        (30,32),
        (31,33),
        (32,34),
        (33,35),
        (34,36),
        (35,37),
        (36,38),
        (37,39),
        (38,40),
        (39,41),
        (40,42),
        (41,43),
        (42,44),
        (43,45),
        (44,46),
        (45,47),
        (46,48),
        (47,49),
        (48,50),
        (49,51);",

        "INSERT INTO SUBGENEROS (NOME, GENERO_ID) VALUES
        ('Desenvolvimento Web', 1),
        ('Redes de Computadores', 1),
        ('Engenharia de Software', 1),
        ('Saude Publica', 2),
        ('Enfermagem', 2),
        ('Engenharia Biomédica', 3),
        ('Pintura', 4),
        ('Escultura', 4),
        ('Historia da Arte', 4),
        ('Antropologia', 5),
        ('Arqueologia', 5),
        ('Empreendedorismo', 6),
        ('Financas', 6),
        ('Pedagogia', 7),
        ('Tecnologia Educacional', 7),
        ('Seguranca da Informacao', 8),
        ('Redes Sociais', 8),
        ('Gastronomia', 9),
        ('Nutrição', 9),
        ('Futebol', 10),
        ('Basquete', 10),
        ('Teoria Musical', 11),
        ('Composição', 11),
        ('Fotografia Digital', 12),
        ('Fotografia Analógica', 12),
        ('Turismo Cultural', 13),
        ('Ecoturismo', 13),
        ('Psicologia Clinica', 14),
        ('Psicologia Organizacional', 14),
        ('Design de Produto', 15),
        ('Design de Moda', 15),
        ('Cinema Documental', 16),
        ('Cinema de Ficção', 16),
        ('Literatura Clássica', 17),
        ('Literatura Contemporânea', 17),
        ('Historia Antiga', 18),
        ('Historia Moderna', 18),
        ('Sociologia Urbana', 19),
        ('Sociologia Rural', 19),
        ('Biologia Molecular', 20),
        ('Ecologia', 20),
        ('Química Orgânica', 21),
        ('Química Inorgânica', 21),
        ('Física Teórica', 22),
        ('Física Experimental', 22),
        ('Álgebra', 23),
        ('Cálculo', 23),
        ('Macroeconomia', 24),
        ('Microeconomia', 24),
        ('Direito Civil', 25),
        ('Direito Penal', 25),
        ('Administração Pública', 26),
        ('Administração Privada', 26),
        ('Marketing Digital', 27),
        ('Marketing Tradicional', 27),
        ('Programação', 28),
        ('Sistemas Operacionais', 28),
        ('Ética', 29),
        ('Lógica', 29),
        ('Sociologia da Educação', 30),
        ('Sociologia do Trabalho', 30),
        ('Cirurgia', 31),
        ('Pediatria', 31),
        ('Medicina Veterinária', 32),
        ('Cuidados com Animais', 32),
        ('Arquitetura Sustentável', 33),
        ('Urbanismo', 33),
        ('Gestão Ambiental', 34),
        ('Conservação Ambiental', 34),
        ('Robótica Industrial', 35),
        ('Robótica de Serviço', 35),
        ('Aprendizado de Máquina', 36),
        ('Redes Neurais', 36),
        ('Neurociência Cognitiva', 37),
        ('Neurociência Comportamental', 37),
        ('Jornalismo Investigativo', 38),
        ('Jornalismo Digital', 38),
        ('Publicidade Online', 39),
        ('Publicidade Tradicional', 39),
        ('Dança Contemporânea', 40),
        ('Dança Clássica', 40),
        ('Teatro Musical', 41),
        ('Teatro Dramático', 41),
        ('Artesanato em Madeira', 42),
        ('Artesanato em Tecido', 42),
        ('Esportes de Aventura', 43),
        ('Esportes Aquáticos', 43),
        ('Culinária Vegana', 44),
        ('Culinária Orgânica', 44),
        ('Viagens de Ecoturismo', 45),
        ('Viagens Culturais', 45),
        ('Futebol de Campo', 46),
        ('Basquete de Rua', 46),
        ('Artes Visuais Digitais', 47),
        ('Animação Digital', 47),
        ('Música Eletrônica de Baile', 48),
        ('Música Eletrônica Experimental', 48),
        ('Cinema Independente Documental', 49),
        ('Cinema Independente de Ficção', 49);",

        "INSERT INTO GRUPOS_MATERIAS (MATERIA_ID, GRUPO_ID) VALUES
        (1, 1),
        (2, 1),
        (3, 2),
        (4, 2),
        (5, 3),
        (6, 3),
        (7, 4),
        (8, 4),
        (9, 5),
        (10, 5),
        (11, 6),
        (12, 6),
        (13, 7),
        (14, 7),
        (15, 8),
        (16, 8),
        (17, 9),
        (18, 9),
        (19, 10),
        (20, 10),
        (1, 11),
        (2, 11),
        (3, 12),
        (4, 12),
        (5, 13),
        (6, 13),
        (7, 14),
        (8, 14),
        (9, 15),
        (10, 15),
        (11, 16),
        (12, 16),
        (13, 17),
        (14, 17),
        (15, 18),
        (16, 18),
        (17, 19),
        (18, 19),
        (19, 20),
        (20, 20),
        (1, 21),
        (2, 21),
        (3, 22),
        (4, 22),
        (5, 23),
        (6, 23),
        (7, 24),
        (8, 24),
        (9, 25),
        (10, 25),
        (11, 26),
        (12, 26),
        (13, 27),
        (14, 27),
        (15, 28),
        (16, 28),
        (17, 29),
        (18, 29),
        (19, 30),
        (20, 30);",

        "INSERT INTO GRUPOS_MATERIAIS (MATERIAL_ID, GRUPO_ID) VALUES
        (1, 1),
        (2, 1),
        (3, 2),
        (4, 2),
        (5, 3),
        (6, 3),
        (7, 4),
        (8, 4),
        (9, 5),
        (10, 5),
        (11, 6),
        (12, 6),
        (13, 7),
        (14, 7),
        (15, 8),
        (16, 8),
        (17, 9),
        (18, 9),
        (19, 10),
        (20, 10),
        (1, 11),
        (2, 11),
        (3, 12),
        (4, 12),
        (5, 13),
        (6, 13),
        (7, 14),
        (8, 14),
        (9, 15),
        (10, 15),
        (11, 16),
        (12, 16),
        (13, 17),
        (14, 17),
        (15, 18),
        (16, 18),
        (17, 19),
        (18, 19),
        (19, 20),
        (20, 20),
        (1, 21),
        (2, 21),
        (3, 22),
        (4, 22),
        (5, 23),
        (6, 23),
        (7, 24),
        (8, 24),
        (9, 25),
        (10, 25),
        (11, 26),
        (12, 26),
        (13, 27),
        (14, 27),
        (15, 28),
        (16, 28),
        (17, 29),
        (18, 29),
        (19, 30),
        (20, 30);",

        "INSERT INTO GRUPOS_SUBGENEROS (SUBGENERO_ID, GRUPO_ID) VALUES
        (1, 1),
        (2, 1),
        (3, 2),
        (4, 2),
        (5, 3),
        (6, 3),
        (7, 4),
        (8, 4),
        (9, 5),
        (10, 5),
        (11, 6),
        (12, 6),
        (13, 7),
        (14, 7),
        (15, 8),
        (16, 8),
        (17, 9),
        (18, 9),
        (19, 10),
        (20, 10),
        (1, 11),
        (2, 11),
        (3, 12),
        (4, 12),
        (5, 13),
        (6, 13),
        (7, 14),
        (8, 14),
        (9, 15),
        (10, 15),
        (11, 16),
        (12, 16),
        (13, 17),
        (14, 17),
        (15, 18),
        (16, 18),
        (17, 19),
        (18, 19),
        (19, 20),
        (20, 20),
        (1, 21),
        (2, 21),
        (3, 22),
        (4, 22),
        (5, 23),
        (6, 23),
        (7, 24),
        (8, 24),
        (9, 25),
        (10, 25),
        (11, 26),
        (12, 26),
        (13, 27),
        (14, 27),
        (15, 28),
        (16, 28),
        (17, 29),
        (18, 29),
        (19, 30),
        (20, 30);",

        "INSERT INTO GRUPOS_GENEROS (GENERO_ID, GRUPO_ID) VALUES
        (1, 1),
        (2, 2),
        (3, 3),
        (4, 4),
        (5, 5),
        (6, 6),
        (7, 7),
        (8, 8),
        (9, 9),
        (10, 10),
        (11, 11),
        (12, 12),
        (13, 13),
        (14, 14),
        (15, 15),
        (16, 16),
        (17, 17),
        (18, 18),
        (19, 19),
        (20, 20),
        (21, 21),
        (22, 22),
        (23, 23),
        (24, 24),
        (25, 25),
        (26, 26),
        (27, 27),
        (28, 28),
        (29, 29),
        (30, 30);",

        "INSERT INTO GRUPOS_USUARIOS (USUARIO_ID, GRUPO_ID) VALUES
        (1, 1),
        (2, 1),
        (3, 2),
        (4, 2),
        (5, 3),
        (6, 3),
        (7, 4),
        (8, 4),
        (9, 5),
        (10, 5),
        (11, 6),
        (12, 6),
        (13, 7),
        (14, 7),
        (15, 8),
        (16, 8),
        (17, 9),
        (18, 9),
        (19, 10),
        (20, 10),
        (21, 11),
        (22, 11),
        (23, 12),
        (24, 12),
        (25, 13),
        (26, 13),
        (27, 14),
        (28, 14),
        (29, 15),
        (30, 15),
        (31, 16),
        (32, 16),
        (33, 17),
        (34, 17),
        (35, 18),
        (36, 18),
        (37, 19),
        (38, 19),
        (39, 20),
        (40, 20),
        (41, 21),
        (42, 21),
        (43, 22),
        (44, 22),
        (45, 23),
        (46, 23),
        (47, 24),
        (48, 24),
        (49, 25),
        (50, 25),
        (51, 26),
        (1, 26),
        (2, 27),
        (3, 27),
        (4, 28),
        (5, 28),
        (6, 29),
        (7, 29),
        (8, 30),
        (9, 30),
        (10, 1),
        (11, 1),
        (12, 2),
        (13, 2),
        (14, 3),
        (15, 3),
        (16, 4),
        (17, 4),
        (18, 5),
        (19, 5),
        (20, 6),
        (21, 6),
        (22, 7),
        (23, 7),
        (24, 8),
        (25, 8),
        (26, 9),
        (27, 9),
        (28, 10),
        (29, 10),
        (30, 11),
        (31, 11),
        (32, 12),
        (33, 12),
        (34, 13),
        (35, 13),
        (36, 14),
        (37, 14),
        (38, 15),
        (39, 15),
        (40, 16),
        (41, 16),
        (42, 17),
        (43, 17),
        (44, 18),
        (45, 18),
        (46, 19),
        (47, 19),
        (48, 20),
        (49, 20),
        (50, 1),
        (51, 1),
        (1, 2),
        (2, 2),
        (3, 3),
        (4, 3),
        (5, 4),
        (6, 4),
        (7, 5),
        (8, 5),
        (9, 6),
        (10, 6),
        (11, 7),
        (12, 7),
        (13, 8),
        (14, 8),
        (15, 9),
        (16, 9),
        (17, 10),
        (18, 10),
        (19, 11),
        (20, 11),
        (21, 12),
        (22, 12),
        (23, 13),
        (24, 13),
        (25, 14),
        (26, 14),
        (27, 15),
        (28, 15),
        (29, 16),
        (30, 16),
        (31, 17),
        (32, 17),
        (33, 18),
        (34, 18),
        (35, 19),
        (36, 19),
        (37, 20),
        (38, 20),
        (39, 1),
        (40, 1),
        (41, 2),
        (42, 2),
        (43, 3),
        (44, 3),
        (45, 4),
        (46, 4),
        (47, 5),
        (48, 5),
        (49, 6),
        (50, 6),
        (51, 7);",

        "INSERT INTO MATERIAIS_GENEROS (GENERO_ID, MATERIAL_ID) VALUES
        (1, 1),
        (2, 2),
        (3, 3),
        (4, 4),
        (5, 5),
        (6, 6),
        (7, 7),
        (8, 8),
        (9, 9),
        (10, 10),
        (11, 11),
        (12, 12),
        (13, 13),
        (14, 14),
        (15, 15),
        (16, 16),
        (17, 17),
        (18, 18),
        (19, 19),
        (20, 20),
        (21, 1),
        (22, 2),
        (23, 3),
        (24, 4),
        (25, 5),
        (26, 6),
        (27, 7),
        (28, 8),
        (29, 9),
        (30, 10),
        (1, 11),
        (2, 12),
        (3, 13),
        (4, 14),
        (5, 15),
        (6, 16),
        (7, 17),
        (8, 18),
        (9, 19),
        (10, 20);",

        "INSERT INTO MATERIAIS_SUBGENEROS (SUBGENERO_ID, MATERIAL_ID) VALUES
        (1, 1),
        (2, 2),
        (3, 3),
        (4, 4),
        (5, 5),
        (6, 6),
        (7, 7),
        (8, 8),
        (9, 9),
        (10, 10),
        (11, 11),
        (12, 12),
        (13, 13),
        (14, 14),
        (15, 15),
        (16, 16),
        (17, 17),
        (18, 18),
        (19, 19),
        (20, 20);",

        "INSERT INTO MATERIAIS_MATERIAS (MATERIA_ID, MATERIAL_ID) VALUES
        (1, 1),
        (2, 2),
        (3, 3),
        (4, 4),
        (5, 5),
        (1, 6),
        (2, 7),
        (3, 8),
        (4, 9),
        (5, 10),
        (1, 11),
        (2, 12),
        (3, 13),
        (4, 14),
        (5, 15),
        (1, 16),
        (2, 17),
        (3, 18),
        (4, 19),
        (5, 20);",

    ],
];
?>